[build-system]

requires = ["setuptools>=42.0.0",
            "setuptools_scm",
            "wheel",
            "cython==3.0.2",
            "extension-helpers==1.*"]

build-backend = 'setuptools.build_meta'
